### ISSUE TITLE
Opentelemetry context propagation

### ISSUE THREAD

**Issue by naseemkullah** [googleapis/java-pubsub#1023]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

**Is your feature request related to a problem? Please describe.**
Would like to stitch together producer, consumer spans **as well as subscriber acknowledgement of message and any processing leading up to the ack.**

**Describe the solution you'd like**
Similar to what is described https://github.com/googleapis/nodejs-pubsub/issues/1389

**Describe alternatives you've considered**
Any alternative solutions or features you've considered.

**Additional context**
Any other context or screenshots about the feature request.

**Comment by naseemkullah** [comment]
According to https://github.com/googleapis/nodejs-pubsub/issues/1389#issuecomment-908455893 this might already be in the works?

**Comment by weyert** [comment]
You might find this a more useful read: https://github.com/googleapis/google-cloud-go/pull/5034
My idea is to do something in pubsub-nodejs

**Comment by naseemkullah** [comment]
> You might find this a more useful read: [googleapis/google-cloud-go#5034](https://github.com/googleapis/google-cloud-go/pull/5034) My idea is to do something in pubsub-nodejs

Thanks @weyert! I posted [this workaround for nodejs](https://github.com/googleapis/nodejs-pubsub/issues/1389#issuecomment-1046396747) maybe it could help

I will try to come up with a similar code snippet for Java in the coming days

**Comment by kamalaboulhosn** [comment]
We are tracking OpenTelemetry support via a ticket in the public issue tracker since it is a cross-language request: issuetracker.google.com/183608476.
