### ISSUE TITLE
Remove @BetaApi decorator for ordering

### ISSUE THREAD

**Issue by anguillanneuf** [googleapis/java-pubsub#1048]
Some APIs for ordering are still tagged as [`@BetaApi`][1] but should be removed now?

https://github.com/googleapis/java-pubsub/blob/eaeedd8bbe31cad3810687a29c5999f76876671d/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/Publisher.java#L320-L321

https://github.com/googleapis/java-pubsub/blob/eaeedd8bbe31cad3810687a29c5999f76876671d/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/Publisher.java#L803-L804

[1]: https://cloud.google.com/java/docs/reference/api-common/latest/com.google.api.core.BetaApi

**Comment by mmicatka** [comment]
Cleaned up. Closing issue.

**Comment by hongalex** [comment]
Strangely enough I still see this. Can we keep this open until these decorators are fully removed?

**Comment by mmicatka** [comment]
I mistakenly thought that I had cleaned this up previously.

Just put a PR together to fix this (linked above).
