### ISSUE TITLE
Memory leak on MpscArrayQueue

### ISSUE THREAD

**Issue by BiatBang** [googleapis/java-pubsub#1055]
#### Environment details

1. java-pubsub
2. OS type and version: GKE with containerd
3. Java version: 11
4.  version(s): com.google.cloud:google-cloud-pubsub:1.115.5

#### Steps to reproduce

I want to record the requests from users. I use Spring interceptor to publish the request to pubsub. Then we have subscription to handle the messages.

The project uses one `publisher` object as a bean. Each request will trigger `publisher.publish(message)`. In the memory heap, I found the following objects are accumulating without gc:

- io.grpc.netty.shaded.io.netty.util.internal.shaded.org.jctools.queues.MpscArrayQueue
- org.apache.tomcat.util.buf.ByteChunk
- org.apache.tomcat.util.buf.CharChunk
- org.apache.tomcat.util.buf.MessageBytes

#### Code example

Publisher initiation:
```
@Bean
public Publisher publisher() {
  TopicName topicName = TopicName.of(projectId, topicId);
  Publisher publisher = null;
  try {
    publisher = Publisher.newBuilder(topicName)
            .build();
  } catch (IOException e) {
    e.printStackTrace();
  }
  return publisher;
}
```

publish message:
```
ByteString data = ByteString.copyFromUtf8(message);
PubsubMessage pubsubMessage = PubsubMessage.newBuilder().setData(data).build();
ApiFuture<String> messageIdFuture = publisher.publish(pubsubMessage);
ApiFutures.addCallback(messageIdFuture, new ApiFutureCallback<String>() {
    public void onSuccess(String messageId) {
        log.info("Published request with message id: {}", messageId);
    }
    public void onFailure(Throwable t) {
        log.warn("Failed to publish metrics: {}", t);
    }
}, MoreExecutors.directExecutor());
```

#### Any additional information below
Traced down the source code and haven't seen how the `publish` is executed. Appreciate it if you can provide some information about how the executor executes the publish action.

Following these steps guarantees the quickest resolution possible.

Thanks!

**Comment by kamalaboulhosn** [comment]
Publish is executed as a standard RPC in gRPC via the [gax library](https://cloud.google.com/java/docs/reference/gax/latest/). If there is some kind of leak, it would likely be at that lower level, though we haven't had any general reports of memory leaks in the client library.
