### ISSUE TITLE
How to properly decode com.google.protobuf.ByteString data message

### ISSUE THREAD

**Issue by rodel0723** [googleapis/java-pubsub#106]
I'm collecting auditlogs export to PubSub services. So I'm using PubSub client to pull subscribe to PubSub subscription. I was able to get the auditlogs using this client. However, some auditlog seems not correctly encoded by the api, so when I use the PubSubMessage.getData().toStringUtf8(), some part of the auditlog was not properly decoded. Please see attached text file.

As you can see in the attached text file, the "fingerprint" part was not decoded correctly.

Now my question is, how can I decode the PubSubMessage data properly?

Note: Same thing is happening when I viewed the auditlog on Google Cloud Platform Logging Console

Thanks,
[samplelog.txt](https://github.com/googleapis/java-pubsub/files/4316460/samplelog.txt)
![samplelog](https://user-images.githubusercontent.com/3927837/76389912-c001ee00-63af-11ea-9e59-d9d40829f53d.png)

**Comment by anguillanneuf** [comment]
@rodel0723 Are these messages published like this?

https://github.com/googleapis/java-pubsub/blob/3d563047ecda9bb1d2300a4eb45740df4ad265f1/samples/snippets/src/main/java/pubsub/PublishWithCustomAttributesExample.java#L49-L58

**Comment by meredithslota** [comment]
I'm going to close this out but feel free to reopen with additional info. Thanks!
