### ISSUE TITLE
Subscriber maxAckExtensionPeriod at zero does not prevent ack deadline extension

### ISSUE THREAD

**Issue by elefeint** [googleapis/java-pubsub#141]
`Subscriber.Builder.setMaxAckExtensionPeriod()`  javadoc [says](https://github.com/googleapis/java-pubsub/blob/4a6046c2b03ad1d7e08d6e6dc0d1817cbffc5283/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/Subscriber.java#L509)  "A zero duration effectively disables auto deadline extensions." But empirically, one 60 second extension is always done.
I made a small command line [example](https://github.com/elefeint/examples/tree/master/pubsub-clientlibrary-ackextension) -- it creates a subscription with default expiration of 30s, publishes a message and waits for it to be delivered and redelivered.

*Expected behavior:* ack deadline never extended, message redelivered after ~30s.
*Actual behavior:* ack deadline extended once with log message "Sending 1 receipts", and message is redelivered after 60 seconds+.

_Some technical details:_
`MessageDispatcher` seems to add each incoming message to its list of ack deadlines (`pendingReceipts`) [regardless of expiration time](https://github.com/googleapis/java-pubsub/blob/9bcc433e6d167f68256e0ede2a521296dcbc7412/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/MessageDispatcher.java#L327). When deadlines get extended, they are extended by `messageDeadlineSeconds`, which [starts at 60 seconds](https://github.com/googleapis/java-pubsub/blob/9bcc433e6d167f68256e0ede2a521296dcbc7412/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/MessageDispatcher.java#L86) and is not controllable by the user application.

Perhaps the reasons for this are historical -- extending ack deadlines happens in two different places: `extendDeadlines()`, which seems to honor the user-set `maxAckExtensionPeriod`, and `processOutstandingAckOperations()`, which talks about "receipts" but actually sends ack deadline modification requests.

This issue is somewhat related to #20, but might end up being just a documentation question if this behavior is intentional.

#### Environment details

Java version: 8
pubsub version(s): 1.104.1

#### Code example

```java
Subscriber.newBuilder(...)
.setMaxAckExtensionPeriod(Duration.ZERO)
.build();
```

Output at FINER level shows:
```
FINER: Sending 1 receipts
```

You can run the whole example (create topic/subscription with 30s ack expiration, publish a message, receive a message without acking or nacking and wait for it to be redelivered):
https://github.com/elefeint/examples/tree/master/pubsub-clientlibrary-ackextension

**Comment by anguillanneuf** [comment]
@kamalaboulhosn @hannahrogers-google You may have more historical context to know if this behavior is intended.

**Comment by hannahrogers-google** [comment]
This is currently how the client behaves, but I would not say this is expected behavior.  When a message is first received by the client, we always immediately send a ModifyAckDeadline request, and we do not take the maxAckExtensionPeriod into account. Creating a fix.
