### ISSUE TITLE
[CONTRIBUTING.md] Add link to Conventional Commits

### ISSUE THREAD

**Issue by SimonScholz** [googleapis/java-pubsub#1506]
I just created the following PR (https://github.com/googleapis/java-pubsub/pull/1505), after reading through your CONTRIBUTING.md.
Then on of the checks of the PR pointed me at the fact that my commit message is not using the [Conventional Commits](https://www.conventionalcommits.org/) guidelines.
To inform contributors about this in advance it would be helpful to add a link to [Conventional Commits](https://www.conventionalcommits.org/).

The change of the CONTRIBUTING.md file can be found here: https://github.com/googleapis/java-pubsub/pull/1507

**Comment by maitrimangal** [comment]
hm, unfortunately it seems like this contributing doc is also autogenerated, and seems to be getting reversed by the post processor. Confirmed internally, and seems like in order to change this we would be changing all the CONTRIBUTING.md docs in the repo for googleapis org.
