### ISSUE TITLE
com.google.cloud.pubsub.v1.StreamingSubscriberConnection$ terminated streaming with exception using java ExecutorService

### ISSUE THREAD

**Issue by kamlesh1808** [googleapis/java-pubsub#1519]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Please run down the following list and make sure you've tried the usual "quick fixes":

  - Search the issues already opened: https://github.com/googleapis/java-pubsub/issues
  - Check for answers on StackOverflow: http://stackoverflow.com/questions/tagged/google-cloud-platform

If you are still having issues, please include as much information as possible:

#### Environment details

1. Specify the API at the beginning of the title. For example, "BigQuery: ...").
   General, Core, and Other are also allowed as types
2. OS type and version: rockylinux-zulu17
3. Java version: Java 17
4.  version(s): 
Spring Boot 2.7.9, spring-cloud-gcp-dependencies: 3.4.5
Google Cloud GKE

#### Steps to reproduce

  1.  A working Spring Boot 2.7.9 application running on GKE that successfully reads message from Google Pubsub using PubSubInboundChannelAdapter and @ServiceActivator. It then peforms a task that can take upto 2-3 minutes. 
  2. Everything work well.
  3. Add java's ExecutorService so that the above task is done concurrently with Callable.
  4. Spring Boot microservice is shutdown after it runs ok for 2-3 minutes. Please see the stack trace below.
  
Notes: I have verified the Pubsub permissions.  The reported behaviour and exception only occurs when using the java ExecutorService for Spring Boot ThreadPoolTaskExecutor within GKE.  The same service does not reproduce when running locally.

#### Code example

```java
// example
```

#### Stack trace
```
at com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:98)
com.google.api.gax.rpc.PermissionDeniedException: com.google.api.gax.rpc.PermissionDeniedException: io.grpc.StatusRuntimeException: PERMISSION_DENIED: User not authorized to perform this action.
ERROR[0;39m [[34mSubscriber-SE-2-2[0;39m] [33mcom.google.cloud.pubsub.v1.StreamingSubscriberConnection$1[0;39m: terminated streaming with exception```

#### External references such as API reference guides

- ?

#### Any additional information below


Following these steps guarantees the quickest resolution possible.

Thanks!

**Comment by kapatelpcln** [comment]
I am looking at the source of the error "terminated streaming with exception" in StreamingSubscriberConnection#initialize() - the call to runShutdown() and a recursive call to initialize() are beyond my comprehension.

**Comment by maitrimangal** [comment]
This is typically an issue with too many requests to the GKE metadata service. To better resolve this issue, please file a support ticket.
