### ISSUE TITLE
How to disable publish retries?

### ISSUE THREAD

**Issue by hdwarakanath** [googleapis/java-pubsub#1593]
[The Publisher code](https://github.com/googleapis/java-pubsub/blob/a6be7b7870ba776fd9b39a0b16d45ba51fcc8ad6/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/Publisher.java#L172) overwrites `maxAttempts` to `Integer.MAX_VALUE` if we set `maxAttempts` to 0. 

How can we disable publish retries in this case?

**Comment by maitrimangal** [comment]
This is being answered internally on YAQs.
But just to write it here as well:

Is there any particular reason customer wants to disable retrying?
We can set the maxAttempts to 1. [This example shows](https://cloud.google.com/pubsub/docs/samples/pubsub-publisher-retry-settings#code-sample) how to do that.
