### ISSUE TITLE
Pub/Sub API docs needs cleanup

### ISSUE THREAD

**Issue by jabubake** [googleapis/java-pubsub#16]
I am fine with minimal information here, but I think its important that it states accurate information.
[Pub/Sub API reference](http://googlecloudplatform.github.io/google-cloud-java/latest/apidocs/index.html?com/google/cloud/pubsub/v1/package-summary.html)

states `TopicAdminClient` is used to send messages to a topic.
`SubscriptionAdminClient` is used to pull messages : Both not true.

**Comment by meredithslota** [comment]
@jabubake Given the evolution of the Pub/Sub client libraries and documentation (including code samples) over the intervening time, I'm tempted to just close this. I'm not totally sure how often an external developer would encounter this issue; if you have additional information or feel strongly about this issue, please feel free to reopen! 

E.g. https://cloud.google.com/pubsub/docs/admin#pubsub-create-topic-java contains information and code samples for `TopicAdminClient` and `SubscriptionAdminClient`.
