### ISSUE TITLE
Inconsistent Message Ordering with High-Frequency Publishing Interval

### ISSUE THREAD

**Issue by rastogirishabh** [googleapis/java-pubsub#1647]
## Issue
When publishing multiple events/message having the same ordering key on a interval of 1 to 500 ms, the message ordering is not maintained consistently. 

Despite taking all the necessary steps to ensure proper ordering, (mentioned below) the consumed events are received out of order.

- publishing messages to a regional end-point.
- enabling message ordering flag at subscription level and 
- enabling message ordering flag at the publisher level.

However, if a sleep delay of approximately 1 second is introduced before publishing the individual events, the messages are received in the expected order.

## Steps to reproduce

1. Set up a publisher-subscriber system with proper configuration for message ordering.
2. Publish a sequence of events with the same ordering key, each separated by a 1 to 500 ms interval. (Don't bring up the consumer yet)
3. Start the consumer that subscribes to a subscription which has message ordering flag enabled.
4. Observe the received order of the consumed events.

### Configurations

```java
  @Bean
  public CredentialsProvider credentialsProvider() {
    return () ->
        ServiceAccountCredentials.fromStream(Files.newInputStream(Paths.get(credentialsFilePath)))
            .createScoped(PublisherStubSettings.getDefaultServiceScopes());
  }

  @Bean
  public PubSubPublisherTemplate pubSubPublisherTemplate(
      CredentialsProvider credentialsProvider, PubSubMessageConverter pubSubMessageConverter) {

    DefaultPublisherFactory factory = new DefaultPublisherFactory(() -> projectId);
    factory.setEnableMessageOrdering(true);
    factory.setCredentialsProvider(credentialsProvider);
    factory.setEndpoint("us-east1-pubsub.googleapis.com:443");

    PubSubPublisherTemplate template = new PubSubPublisherTemplate(factory);
    template.setMessageConverter(pubSubMessageConverter);
    return template;
  }

  @Bean
  public PubSubSubscriberTemplate subscriberTemplate(
      CredentialsProvider credentialsProvider, PubSubMessageConverter pubSubMessageConverter) {

    GcpPubSubProperties gcpPubSubProperties = new GcpPubSubProperties();
    gcpPubSubProperties.setKeepAliveIntervalMinutes(1);
    gcpPubSubProperties.initialize(projectId);

    DefaultSubscriberFactory factory =
        new DefaultSubscriberFactory(() -> projectId, gcpPubSubProperties);
    factory.setCredentialsProvider(credentialsProvider);

    PubSubSubscriberTemplate template = new PubSubSubscriberTemplate(factory);
    template.setMessageConverter(pubSubMessageConverter);
    return template;
  }

  @Bean
  public PubSubTemplate pubSubTemplateBean(
      PubSubPublisherTemplate pubSubPublisherTemplate,
      PubSubSubscriberTemplate subscriberTemplate) {
    return new PubSubTemplate(pubSubPublisherTemplate, subscriberTemplate);
  }
```

### Publisher and Subscriber

```java
  private void publishWithOrdering(List<Item> items) {
    items.forEach(
        item -> {
          log.info(
              "Publishing item (with ordering key) : [{}] with event description : [{}] ",
              item.getItemNumber(),
              item.getItemDescription());

          pubSubTemplate.publish(
              topic(), item, Collections.singletonMap(GcpPubSubHeaders.ORDERING_KEY, "1234"));

          try {
            Thread.sleep(100);
          } catch (InterruptedException e) {
            throw new RuntimeException(e);
          }
        });
  }

@Configuration
public class PubSubListener {
  @Bean
  public Subscriber itemListener(PubSubTemplate pubSubTemplate) {

    return pubSubTemplate.subscribeAndConvert(getSubscription(), this::handleMessage, Item.class);
  }

  public void handleMessage(ConvertedBasicAcknowledgeablePubsubMessage<Item> message) {
    Item payload = message.getPayload();
    log.info(
        "Item received with item ID : [{}] and event description : [{}] with ordering key [{}]",
        payload.getItemNumber(),
        payload.getItemDescription(),
        message.getPubsubMessage().getOrderingKey());

    message.ack();
  }

  public String getSubscription() {
    return "item-topic-subscription";
  }
}
```

## Dependencies

```maven
<dependencyManagement>
  <dependencies>
    <dependency>
      <groupId>com.google.cloud</groupId>
      <artifactId>spring-cloud-gcp-dependencies</artifactId>
      <version>4.5.1</version>
      <type>pom</type>
      <scope>import</scope>
    </dependency>
  </dependencies>
</dependencyManagement>

<dependency>
  <groupId>com.google.cloud</groupId>
  <artifactId>spring-cloud-gcp-starter-pubsub</artifactId>
</dependency>

<dependency>
  <groupId>com.google.cloud</groupId>
  <artifactId>spring-cloud-gcp-starter</artifactId>
</dependency>

```

**Comment by maitrimangal** [comment]
Taking a look at this seems like the steps followed [here]( https://github.com/GoogleCloudPlatform/spring-cloud-gcp/blob/186a1500d7951d04a4f2ff4b386312c93ca1ecb2/docs/src/main/asciidoc/pubsub.adoc#ordering-messages) seem to be correct. Might need to transfer to the spring java pubsub team to look deeper into this.

**Comment by maitrimangal** [comment]
Hi actually, can you please post this bug [here](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/issues). Since this is Spring Java Pubsub they will be able to help you over there. Thanks

**Comment by rastogirishabh** [comment]
Issue raised on spring-cloud-gcp board. https://github.com/GoogleCloudPlatform/spring-cloud-gcp/issues/2008

**Comment by meltsufin** [comment]
@maitrimangal We think that the issue is in the `Publisher` itself. It doesn't seem to allow asynchronous publishing. Is that correct? The [official documentation](https://cloud.google.com/pubsub/docs/samples/pubsub-publish-with-ordering-keys) doesn't explicitly say that you have to wait for the publish future to complete before sending the next message. Are we mistaken here, or are the docs incomplete?

**Comment by meltsufin** [comment]
Never mind, we were actually using a different Publisher instance each time.
