### ISSUE TITLE
Expose ProxyDetector from gRPC library

### ISSUE THREAD

**Issue by pvillard31** [googleapis/java-pubsub#193]
Thanks for stopping by to let us know something could be better!

**Is your feature request related to a problem? Please describe.**
There is no way to define proxy parameters without defining variables at the JVM level which can create side effects for systems running in the same JVM.

**Describe the solution you'd like**
I opened a feature request on grpc/grpc-java#7043 and they suggested to use ``ProxyDetector`` but I didn't find a way to leverage this in the PubSub client.

**Describe alternatives you've considered**
Running things in different JVMs but that's a no-go for us.

**Additional context**
Any other context or screenshots about the feature request.

**Comment by ejona86** [comment]
gRPC has a `ManagedChannelBuilder.proxyDetector(io.grpc.ProxyDetector)` method that can be used to configure this. I see there is a [`InstantiatingGrpcChannelProvider.Builder.setChannelConfigurator()`](https://javadoc.io/static/com.google.api/gax-grpc/1.56.0/com/google/api/gax/grpc/InstantiatingGrpcChannelProvider.Builder.html#setChannelConfigurator-com.google.api.core.ApiFunction-) method that could be used in gax-java, but I'm not familiar with how the pubsub API and gax-java interact.

**Comment by hannahrogers-google** [comment]
The pubsub Publisher and Subscriber classes expose a setChannelProvider method in the clients that allows users to customize the gax TransportChannelProvider.

Ex. 
```
Publisher publisher = Publisher.newBuilder(topicName)
    .setChannelProvider(
        InstantiatingGrpcChannelProvider.newBuilder()
            .setChannelConfigurator(managedChannelBuilder -> managedChannelBuilder.proxyDetector(...))
    ...
    .build();
```

To customize the TransportChannelProvider for the TopicAdminClient and SubscriptionAdminClient, users can do the following:

```
SubscriptionAdminSettings subscriptionAdminSettings =
     SubscriptionAdminSettings.newBuilder()
         .setTransportChannelProvider(
             InstantiatingGrpcChannelProvider.newBuilder()...)
         .build();
 SubscriptionAdminClient subscriptionAdminClient =
     SubscriptionAdminClient.create(subscriptionAdminSettings);
 ```
