### ISSUE TITLE
Message ordering seems to have been broken between 1.125.13 and 1.126.0

### ISSUE THREAD

**Issue by burkedavison** [googleapis/java-pubsub#1954]
Customer has raised in ticket in Spring Cloud GCP with a replicator project using the emulator demonstrating an issue with message ordering:
* Working version using Spring Cloud GCP 5.0.0 bundled with java-pubsub 1.125.13
* Broken version using Spring Cloud GCP 5.0.1 bundled with java-pubsub 1.126.0
* Working version using Spring Cloud GCP 5.0.1 with hardcoded java-pubsub 1.125.13

> The problem is present in 5.0.1 [bundled with java-pubsub 1.126.0], 5.0.2 [bundled with java-pubsub 1.126.2], 5.0.3 [bundled with java-pubsub 1.126.5], and 5.0.4 [bundled with java-pubsub 1.126.6].

Original issue: https://github.com/GoogleCloudPlatform/spring-cloud-gcp/issues/2649
* Contains replicator project: https://github.com/ls-urs-keller/pubsub-message-ordering-problem

**Comment by michaelpri10** [comment]
@burkedavison 
This was an issue that required an update in the Pub/Sub emulator that was fixed in version 0.8.12 of the Pub/Sub emulator. Could you ask the customer to upgrade their version of the emulator?

**Comment by michaelpri10** [comment]
Per [this comment](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/issues/2649#issuecomment-2006856063), the user confirmed that upgrading the emulator version fixed the message ordering issue.
