### ISSUE TITLE
Support for OpenTelemetry for Pubsub messages

### ISSUE THREAD

**Issue by jfbenckhuijsen** [googleapis/java-pubsub#1981]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

**Is your feature request related to a problem? Please describe.**
I'm looking at solving the OpenTelemtry feature request for the Quarkus Google Cloud extensions (see issue https://github.com/quarkiverse/quarkus-google-cloud-services/issues/451) and wonder if support for OTEL is planned or already being worked on for the Java client library

**Describe the solution you'd like**
Preferebly I would assume we would like to have OTEL support in Pubsub-java itself, instead of providing this manually from the extension (as than multiple frameworks in the ecosystem can benefit from it, not just Quarkus).

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by michaelpri10** [comment]
Hello! We do have plans to add Open Telemetry integration into this library and work on it will be beginning soon.

**Comment by michaelpri10** [comment]
Hello @kamil-dobrzynski, the Open Telemetry implementation is currently under review at https://github.com/googleapis/java-pubsub/pull/2086. We hope to have it released in the coming weeks.

**Comment by michaelpri10** [comment]
OpenTelemetry support has been released in [v1.133.0](https://github.com/googleapis/java-pubsub/releases/tag/v1.133.0)!
