### ISSUE TITLE
***@***.***

### ISSUE THREAD

**Issue by alopablo** [googleapis/java-pubsub#1988]
***@***.***

_Publicado originalmente por @alopablo en https://github.com/googlemaps/google-maps-services-java/issues/974#issuecomment-2048803645_

**Comment by michaelpri10** [comment]
Hello! To file a bug report or feature request, please do so following the appropriate templates. If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub.
