### ISSUE TITLE
Protobuf V4 compatibility

### ISSUE THREAD

**Issue by bjoernmayer** [googleapis/java-pubsub#1996]
**Is your feature request related to a problem? Please describe.**
protobuf-java had a major release: See [here](https://protobuf.dev/news/2023-12-05/). 
In this release `GeneratedMessageV3` was renamed to `GeneratedMessage`.

It is therefore impossible to use the generated java classes like [PubsubMessage](https://github.com/googleapis/java-pubsub/blob/main/proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/PubsubMessage.java) in projects with protobuf v4 as `GeneratedMessageV3` cannot be found.

**Describe the solution you'd like**
Update your `protobuf-java` version to v4 and recompile the `.proto` files.

**Describe alternatives you've considered**
None

**Comment by emintz** [comment]
Could you please post a work-around? Thank you.

**Comment by bjoernmayer** [comment]
Protobuf java is about to add shims, that make v4 compatible with v3 generated files:
https://github.com/protocolbuffers/protobuf/issues/17247

**Comment by emintz** [comment]
Thank you. Do we know how long this might take?

**Comment by bjoernmayer** [comment]
Protobuf v27.4 fixed this issue.
As soon as v28 currently (RC release) is released, I will close this issue

**Comment by bjoernmayer** [comment]
Protobuf v27.4 and v28 fix this issue.

Closing!
