### ISSUE TITLE
Dependency with CVE please upgrade

### ISSUE THREAD

**Issue by jimshowalter** [googleapis/java-pubsub#2198]
com.google.cloud:google-cloud-pubsub:1.132.2 has a dependency on com.google.protobuf:protobuf-java:3.25.4.

All of the 3.x.y series have CVEs.

The only version that doesn't have a CVE is the latest 4.x.y: https://mvnrepository.com/artifact/com.google.protobuf/protobuf-java/4.28.2.

Please upgrade google-cloud-pubsub to use that version of protobuf-java.

**Comment by michaelpri10** [comment]
Hello! The protobuf-java version has recently been upgraded to 3.25.5 which has [resolved all CVEs](https://deps.dev/maven/com.google.protobuf%3Aprotobuf-java/3.25.5), and the generated Java proto files in this repository use protobuf-java v3.25.5 for all library versions greater than v1.132.2. Resolving this issue, but if you find evidence that 3.25.5 also contains the CVE, please re-open and provide the CVE name. Thank you!

**Comment by jimshowalter** [comment]
Thank you!
