### ISSUE TITLE
Use @Deprecated tag in TopicAdminClient and SubscriptionAdminClient

### ISSUE THREAD

**Issue by pradn** [googleapis/java-pubsub#249]
https://github.com/googleapis/java-pubsub/blob/97c08246e00f20314b2d2e3dc4542007edecefa3/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/TopicAdminClient.java#L260

When pulling the Java library into Google's source tree, lint errors are being thrown in TopicAdminClient and SubscriptionAdminClient..

third_party/java_src/cloud/pubsub/client/src/main/java/com/google/cloud/pubsub/v1/TopicAdminClient.java:260: error: [DepAnn] Item documented with a @deprecated javadoc note is not annotated with @Deprecated
  public final Topic createTopic(ProjectTopicName name) {
                     ^
    (see http://go/bugpattern/DepAnn)
  Did you mean '@Deprecated'?

We need to add a @Deprecated annotation to all the fields in that file with a "@deprecated" docs note.

**Comment by hannahrogers-google** [comment]
These are generated from the gapic generator, which is unable to parse the comments to determine if something is deprecated.  We will probably have to contact the AC Tools team for guidance on this issue.

**Comment by meredithslota** [comment]
I'm assigning this to @stephaniewang526 to help connect y'all — we are starting some Java generator work and she can help route this.

**Comment by stephaniewang526** [comment]
@vam-google could you please see if you are able to help with this ticket? Thank you!

**Comment by miraleung** [comment]
The `deprecated` tags are being added in post-processing [here](https://github.com/googleapis/java-pubsub/blob/master/synth.py), so any parameter tags would need to be added there as well. This all happens after the Java microgenerator has produced this code.

**Comment by vam-google** [comment]
+1 to @miraleung 's comment. The whole deprecation logic is in [synth.py](https://github.com/googleapis/java-pubsub/blob/master/synth.py), so we should just add the `@Deprecated` annotation to the methods right after the `@deprecated` documentation tag in the replacements made in synth.py (for example add `@Deprecated` annotation right at the line [45](https://github.com/googleapis/java-pubsub/blob/master/synth.py#L45) to fix the `getIamPolicy` linter error). The synth.py file is owned by Yoshi.

**Comment by stephaniewang526** [comment]
Hi @hannahrogers-google,

As @miraleung and @vam-google from ACTools commented, this is not a generator-related issue.

The fix would need to be done in `synth.py` to add in `@deprecated` tags to all the fields in `TopicAdminClient.java` with a `@deprecated` docs note.

@yihanzhen helped make the `synth.py` changes [last time](https://github.com/googleapis/java-pubsub/commit/4558c3430901cdaec12a43e06ea4fafaa01c08e0) -- perhaps he could help answer any questions regarding making another round of similar changes.

@chingor13 from Yoshi could also help with giving directions on how to modify `synth.py`.

Assigned this ticket back to pubsub client library owner for next steps. cc @meredithslota

**Comment by yihanzhen** [comment]
Looks like you just need to add the annotation here: https://github.com/googleapis/java-pubsub/blob/master/synth.py#L244

**Comment by hannahrogers-google** [comment]
Thanks all! Creating a PR
