### ISSUE TITLE
Cloud Function Java Background Function Support

### ISSUE THREAD

**Issue by wko27** [googleapis/java-pubsub#314]
We are using the relatively recent [Java 11 Cloud Functions](https://cloud.google.com/blog/products/application-development/introducing-java-11-on-google-cloud-functions) and following the [quickstart tutorials](https://cloud.google.com/functions/docs/writing/background).

Having used this PubSub library previously, I assumed that the following two libraries played well with each other:

```
<dependency>
      <groupId>com.google.cloud</groupId>
      <artifactId>google-cloud-pubsub</artifactId>
      <version>1.108.1</version>
    </dependency>
```

```
<dependency>
      <groupId>com.google.cloud.functions</groupId>
      <artifactId>functions-framework-api</artifactId>
      <version>1.0.1</version>
      <scope>provided</scope>
    </dependency>
```

This does NOT seem to be the case, i.e. the BackgroundFunction type parameter PubSubMessage MUST be a simple POJO and can not be the com.google.pubsub.v1.PubsubMessage class.

We were able to successfully deploy cloud functions with the type signature BackgroundFunction<PubSubMessage> but found runtime failures where the PubsubMessage's field variables were not populated.

This is both a documentation request to clarify that this library should NOT be used with the new Java Cloud functions library, and/or a feature request to add support so that the two libraries are indeed compatible.

**Comment by anguillanneuf** [comment]
👋  @wko27 Thank you for trying out the blogpost and tutorial!

Unfortunately the two libraries don't play well together currently, and we've also seen similar issues with `functions-framework-nodejs`: 
https://github.com/GoogleCloudPlatform/functions-framework-nodejs/issues/41
https://github.com/GoogleCloudPlatform/functions-framework-nodejs/issues/96

@grant @ace-n I think a note on [`functions-framework-java`](https://github.com/GoogleCloudPlatform/functions-framework-java) on is probably more appropriate than putting it in this repo. Wdyt? 

Cc: @glaforge

**Comment by glaforge** [comment]
Cc @eamonnmcmanus as well

**Comment by meredithslota** [comment]
Based on @anguillanneuf's comment, I'm going to transfer this to the `functions-framework-java` repo. Please let me know if this is incorrect.

**Comment by meredithslota** [comment]
Hilariously, I cannot (don't have right permissions). @eamonnmcmanus can you?

**Comment by eamonnmcmanus** [comment]
I don't have write permission to this repo (`googleapis/java-pubsub`) so I can't transfer the issue. @meredithslota I've sent you an invite with write access to `functions-framework-java` which will probably allow you to do the transfer.

**Comment by anguillanneuf** [comment]
@wko27 @eamonnmcmanus @meredithslota With https://github.com/GoogleCloudPlatform/functions-framework-java/pull/98, Functions Framework works with Pub/Sub emulator in Java now. I have tested this myself and written down the steps that have worked for me: https://github.com/anguillanneuf/PubSubEmulatorExamples#java
