### ISSUE TITLE
Local PubSub Helper

### ISSUE THREAD

**Issue by lucasoares** [googleapis/java-pubsub#32]
I would like a class like the [LocalDatastoreHelper ](https://github.com/googleapis/google-cloud-java/blob/master/google-cloud-clients/google-cloud-datastore/src/main/java/com/google/cloud/datastore/testing/LocalDatastoreHelper.java) to start the PubSub Emulator directly from my code.

I want to contribute on this if you guys plan to continue supporting this kind of feature.

Thanks.

**Comment by lucasoares** [comment]
> Any updates on this? We have more users asking for this feature.
> [GoogleCloudPlatform/spring-cloud-gcp#333](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/issues/333)

@meltsufin unfortunately I had no time looking into this, we will need, for now, another contributor for this.

**Comment by meltsufin** [comment]
@lucasoares I was more asking the project maintainers. 😄

**Comment by hannahrogers-google** [comment]
This is not something that we plan to support.  However, we do have a plan to create better mocks that can be used instead of the emulator for local unit testing.  Progress on this feature can be tracked via our [issue tracker](https://b.corp.google.com/issues/181876876).
