### ISSUE TITLE
Pub/Sub client doesn't reconnect after a permission denied error

### ISSUE THREAD

**Issue by olivierboudet** [googleapis/java-pubsub#330]
**Is your feature request related to a problem? Please describe.**
When removing the role 'PubSub Subscriber' to the service account used by the application, an expected exception PermissionDeniedException is thrown after few secondes or minutes. Then, if the role is re-added to the service account, the connection is not reopened by the client.

**Describe the solution you'd like**
It could be useful if the client can reconnect after a change in the IAM configuration (errors happens... :) ). I initially thought that the option keep-alive-interval-minutes: 5 could be used on permission denied error but it has no effect.

**Additional context**
I have a sample repro application here : https://github.com/olivierboudet/test-pubsub-gcp-issue

**Steps to reproduce**

1. Modify application.properties to set the project name, the subscription name and the encoded credential key
2. Start the application
3. Remove the role 'PubSub Subscriber' to the service account used by the application
4. Wait for the PermissionDeniedException exception
5. Add the role 'PubSub Subscriber' to the service account used by the application
6. Publish a message in the corresponding topic

The message is never consumed by the application. It needs to be restarted.

**Comment by hongalex** [comment]
Per our [best practices](https://google.aip.dev/194), permission denied is not a retryable error. This is not a common pattern that we expect to see, and if you anticipate encountering this in your application, we recommend doing application layer retry.
