### ISSUE TITLE
Reuse  Publisher instance

### ISSUE THREAD

**Issue by michmzr** [googleapis/java-pubsub#343]
Hi,

I have a question about reusing Publisher object in publishing example:

```java
Publisher publisher = null;
try {
  publisher = Publisher.newBuilder(topic).build();
  ByteString data = ByteString.copyFromUtf8("my-message");
  PubsubMessage pubsubMessage = PubsubMessage.newBuilder().setData(data).build();
  ApiFuture<String> messageIdFuture = publisher.publish(pubsubMessage);
  ApiFutures.addCallback(messageIdFuture, new ApiFutureCallback<String>() {
    public void onSuccess(String messageId) {
      System.out.println("published with message id: " + messageId);
    }

    public void onFailure(Throwable t) {
      System.out.println("failed to publish: " + t);
    }
  }, MoreExecutors.directExecutor());
  //...
} finally {
  if (publisher != null) {
    publisher.shutdown();
    publisher.awaitTermination(1, TimeUnit.MINUTES);
  }
}
```
When multiple events (thousands, milions) are sent, then each time a new Publisher is created and takes a Thread. Whats a general approach to asynchronously send a big amount of events?

What do you think to keep Publisher instance in cache/static field and do not shutdown? Whats a optimum time for `awaitTermination`

**Comment by michalbrzezinskiorg** [comment]
same question

**Comment by chrisribble** [comment]
I opened a similar issue a while back: https://github.com/googleapis/java-pubsub/issues/86

**Comment by hannahrogers-google** [comment]
That is correct. We have opened an [issue](https://issuetracker.google.com/issues/154851748) in our public issue tracker to add support to our Publisher client to allow users to publish to multiple topics.
