### ISSUE TITLE
Atomic Batch Publish

### ISSUE THREAD

**Issue by gpoulin** [googleapis/java-pubsub#486]
**Is your feature request related to a problem? Please describe.**
The RPC Publish [signature](https://cloud.google.com/pubsub/docs/reference/rpc/google.pubsub.v1#google.pubsub.v1.Publisher.Publish) suggests that it should be possible to publish a list of message atomically, whether they all succeed or they all fail. If it's the case, it should be exposed in the `Publisher` java interface as there is many situation where it could be useful.

**Describe the solution you'd like**
Expose a method `ApiFuture<List<String>> atomicPublish(List<PubsubMessage> messages)` in the `Publisher` class. This method would be equivalent to calling `publish` on all messages in the list, but would ensure that all message in the list are part of the same `MessagesBatch`. This method should throw an exception if:

  - There's more than a 1000 messages in the list
  - The total serialized size is over 10 MB
  - The messages contains more than one distinct ordering key

**Describe alternatives you've considered**
Alternatively, it's possible to call the `publish` method from the `GrpcPublisherStub`. However it requires to setup and maintain a distinct client as the one used by `Publisher` is not exposed. It also doesn't benefit from the batching logic from the `Publisher`.

**Comment by meltsufin** [comment]
For those who do not want to rely on the automated batching in `Publisher`, what is the currently recommended workaround?
Is it to call `publish` multiple times and then call `publishAllOutstanding`, while keeping the automated batch size as large as possible?

cc: @vy @breun @mzeijen @dzou @ttomsu

**Comment by kamalaboulhosn** [comment]
There is currently no batch atomic publish available in the Cloud Pub/Sub service. Even messages published in the same batch are not guaranteed to be treated atomically and succeed in an all-or-nothing fashion. This feature is not one we anticipate adding to Cloud Pub/Sub at this time. 

If one does want to manage published batches on one's own, the only option is to use the underlying auto-generated gRPC library and manually create PublishRequest objects with messages batched. Note that the batches delivered to subscribers may not contain all of the messages sent together in the same batch.

**Comment by vy** [comment]
Thanks for the response @kamalaboulhosn. Would you mind sharing your thoughts regarding the following questions, please?
1. Publishing multiple messages via gRPC `PublishRequest` is all-or-nothing, correct?
2. Mind sharing the rationale behind not exposing this feature in the Java API? Is there a technical reason for this decision?

**Comment by kamalaboulhosn** [comment]
It is currently all-or-nothing, but that is not a guarantee ever given by Cloud Pub/Sub and there is the possibility that this behavior could change. I would not recommend building anything on the assumption that it is all-or-nothing. We didn't expose it just because the client library is designed to be higher level in nature and offer the API we see as the typical use case. For those who need more exact control, there is still always the option of using the auto-generated gRPC library.

**Comment by meltsufin** [comment]
@kamalaboulhosn Despite the lack of all-or-nothing guarantee, there might be a benefit to the user to control the round-trips from the app to the server. Batch publish without all-or-nothing guarantee would allow this. @vy Is this something that is useful for your usecases?

**Comment by kamalaboulhosn** [comment]
@meltsufin This can be done with the auto-generated library, correct? It just can't be done with this hand-written library. And that is by design, really. If one needs more exact control over the exact requests to the server, use the GAPIC auto-generated library.

**Comment by meltsufin** [comment]
@kamalaboulhosn Yes, I think it can be done, but I don't think you can easily mix the use of the higher level library and the auto-generated one. For instance, the `Publisher` class has the `PublisherStub` as a field, but it doesn't provide a getter for it. I might be missing something here though.

**Comment by kamalaboulhosn** [comment]
@meltsufin I wouldn't expect someone to mix usage of the two in any particular instance. One would use either one or the other in any given use case.

**Comment by meltsufin** [comment]
@kamalaboulhosn In Spring Cloud GCP we decided to go with the manual layer, which is much easier to use and configure. This leaves use without an easy way to expose the `PublisherStub`.
