### ISSUE TITLE
Subscriber: message delivery suddenly pauses

### ISSUE THREAD

**Issue by frekw** [googleapis/java-pubsub#490]
Thanks for stopping by to let us know something could be better!

We're seeing some issues with the Java Pub/Sub client for a subscription with quite low message rates. 

The PubSub client will consume messages normally for roughly 30 minutes. Then all message delivery  suddenly halts for 90-120 minutes, only to resume for 30 minutes and then halt. And then it repeats.

#### Environment details

- The subscription and topic have message ordering enabled
- We use google-cloud-pubsub @ 1.110.3
- We ack every message we receive
- We aren't seeing any exceptions getting thrown
- We run a single pod in GKE, so flow control shouldn't be an issue
- Our setup is very similar to the PubSub examples in the documentation (i.e we're using SubscriberStubSettings.defaultTransportChannelProvider)
- We've tried a bunch of different executor providers without any observable difference
- Restarting the pod will immediately resume message delivery
- JRE11

#### Code example

This is basically the code we're running

```scala
val recv: MessageReceiver =
    (m: PubsubMessage, ack: AckReplyConsumer) => {
        println(s"got message: ${m.getData().toStringUtf8()}")
        ack.ack()
    }

val executorProvider = InstantiatingExecutorProvider
    .newBuilder()
    .setExecutorThreadCount(4)
    .build()

val subscriber = Subscriber
    .newBuilder(name, receiver)
    .setChannelProvider(SubscriberStubSettings.defaultTransportChannelProvider)
    .setCredentialsProvider(credsProvider)
    .setExecutorProvider(executorProvider)
    .setSystemExecutorProvider(executorProvider)
    .build
    subscriber.addListener(
        new Listener {
            override def failed(
                state: State,
                t: Throwable
            ): Unit = {
                println(s"pubsub failed: ${t}")
            }
        },
        executorProvider.getExecutor()
    )
subscriber.startAsync().awaitRunning()
```

Here's what the graphs look like. I've done some digging in Stackdriver metrics as well but have been unable to come up with anything interesting.

![graph](https://i.imgur.com/EOWHR0s.png)

#### Any additional information below

I have a support case open (#26603590) in which further information, such as topic and subscription IDs, can be found.

Thanks!

**Comment by meredithslota** [comment]
Hi there! Thanks for filing an issue — the engineers who work in this project won't have access to your topic and subscription IDs but we can see the internal support issue you referenced; we'll keep an eye on that (I see already someone working on it) and if it does seem like a bug in the library we'll try to repro and figure out a resolution.

**Comment by meredithslota** [comment]
Still keeping tabs on what's happening in the support ticket, marking this ticket as "external" since we're waiting on additional info from support. Thanks!

**Comment by frekw** [comment]
To follow up on this:

It seems like the cause was `SubscriberStubSettings.defaultTransportChannelProvider` not specifying a keep alive timeout.

Adding the following fixed the issue I was having:

```
SubscriberStubSettings.defaultGrpcTransportProviderBuilder
              .setKeepAliveTime(
                Duration.ofSeconds(60L * 5L)
              )
              .build()
```

However, I do find it very surprising that `SubscriberStubSettings.defaultTransportChannelProvider` doesn't actually include all the defaults needed for a subscriber to work properly. As a user of the library, I would probably consider this as a bug.

This root issue from the point of view of a library consumer is actually #308. In order to minimize the different code paths we run we more or less do the following:

```scala
  def channelProvider =
    sys.env.get("PUBSUB_EMULATOR_HOST") match {
      case None =>
            SubscriberStubSettings.defaultGrpcTransportProviderBuilder
              .setKeepAliveTime(
                Duration.ofSeconds(60L * 5L)
              )
              .build()
      case Some(hostPort) =>  FixedTransportChannelProvider.create(GrpcTransportChannel.create(ManagedChannelBuilder.forTarget(hostPort).usePlaintext().build()))
    }
```

and use that when creating the subscription client. If the Java client respected the `PUBSUB_EMULATOR_HOST` we wouldn't have run into this in the first place.

**Comment by hannahrogers-google** [comment]
Thank you for the feedback! We will track the feature request to use PUBSUB_EMULATOR_HOST in issue#308.

**Comment by frekw** [comment]
Alright!

I would also consider adding a keep alive timeout to `SubscriberStubSettings.defaultTransportChannelProvider` before considering this fully fixed. It's still quite easy for someone else to run into the same issue I did.
