### ISSUE TITLE
com.google.pubsub.v1.ProjectTopicName is deprecated

### ISSUE THREAD

**Issue by lpellegr** [googleapis/java-pubsub#58]
Using version _v1.102.1_, I see some deprecated classes.

In the generated documentation I don't see any explanation to fix deprecated API usages. Besides, this project README is using deprecated code as examples: 

https://github.com/googleapis/java-pubsub#creating-a-topic

The recent changelog mentions nothing:

https://github.com/googleapis/java-pubsub/blob/master/CHANGELOG.md

and the releases page brings nothing:

https://github.com/googleapis/java-pubsub/releases

Any guidance or an up-to-date example in the README and a mention in the changelog would be really helpful.

**Comment by kamalaboulhosn** [comment]
@chingor13 PR #40 marked several widely used classes as deprecated, e.g., ProjectTopicName. Is that expected? I'm not even sure from which proto ProjectTopicName is generated.

**Comment by petarov** [comment]
I have noticed the deprecated `ProjectTopicName` class my code today. Doesn't seem right and there's not info on what to use in place of it. 🤔 

`google-cloud-pubsub:1.102.1`

```java
/**
 * AUTO-GENERATED DOCUMENTATION AND CLASS
 *
 * @deprecated This resource name class will be removed in the next major version.
 */
@javax.annotation.Generated("by GAPIC protoc plugin")
@Deprecated
public class ProjectTopicName extends TopicName {
```

**Comment by cfetterolf** [comment]
+1, I noticed the same thing today.  Is this deprecation of `ProjectTopicName` intentional?  If so, what should be used in its place?

**Comment by NuwanSameera** [comment]
google-cloud-pubsub:1.103.0 also deprecated **ProjectTopicName** class. Is there any replacement class for this.

**Comment by hzyi-google** [comment]
Hi everyone. Sorry for the confusion of the deprecated information without the alternatives.

We will have a single concrete `TopicName` class soon, with which you could do:

```java
TopicName topicName = topicName.createProjectTopicName("my-project", "my-topic");
System.out.println(topicName.toString()); // "projects/my-project/topics/{my-topic}"

topicName = topicName.createDeletedTopicName();
System.out.println(topicName.toString()); // "_deleted-topic_"

String topic = topicName.formatProjectTopicName("my-project", "my-topic");
System.out.println(topic);  // "projects/my-project/topics/{my-topic}"
```

This new design of resource names would be more scalable for us as we have more and more resources with more than one patterns and originally single-pattern resources gaining new patterns, where it's been hard to come up with descriptive and consistent class names for each resource name subclass.

We are rolling out the change to client libraries one by one. And because of PubSub is huge we want to be extra careful :confused: and make sure the new library is backward-compatible until we are ready for 2.0, so it's taking a long time to roll the new PubSub out :stuck_out_tongue_closed_eyes:

**Comment by kamalaboulhosn** [comment]
It seems as though the addition of the deprecated tag was done prematurely. As @hzyi-google points out, there is a migration ongoing to the way topic names are generated, but we need to make sure examples and documentation are updated accordingly before marking the field deprecated. We will soon revert the change that marked these deprecated until the new way to do things is fully documented.

**Comment by intellprojects** [comment]
TopicName topicName = topicName.createProjectTopicName("my-project", "my-topic");
does not compile...

**Comment by hzyi-google** [comment]
@intellprojects sorry for the confusion - but the new helpers are released yet. We are working on it :)

**Comment by dmytro-kashcheiev** [comment]
>  until we are ready for 2.0, so it's taking a long time to roll the new PubSub out 😝
Are you talking about Pub/Sub 2.0 or about all clients' libraries 2.0 ?

**Comment by kamalaboulhosn** [comment]
> Are you talking about Pub/Sub 2.0 or about all clients' libraries 2.0 ?

Client libraries 2.0.

**Comment by benzhang94** [comment]
@kamalaboulhosn It seems the latest release `1.103.1` did not package your PR change in - https://github.com/googleapis/java-pubsub/blob/v1.103.1/proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/ProjectTopicName.java.

**Comment by kamalaboulhosn** [comment]
Indeed. It looks like 104 will pick it up, though https://github.com/googleapis/java-pubsub/blob/release-v1.104.0/proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/ProjectTopicName.java.
