### ISSUE TITLE
Default maxAckExtensionPeriod should be ZERO

### ISSUE THREAD

**Issue by anthavio** [googleapis/java-pubsub#637]
**Is your feature request related to a problem? Please describe.**
When I create subscription
`gcloud pubsub subscriptions create some-subscription --topic=some-topic --ack-deadline=30`
and use simple Subscriber initialization
```
//scala
val subscription = ProjectSubscriptionName.of(projectId, subscriptionId)
val subscriber = Subscriber.newBuilder(subscription, receiver).build
```
and in my MessageReceiver.receiveMessage I neither ack nor nack message, it will be redelivered after 1 hour!
I'd expect message redelivery attempt to happen after 30 seconds as subscription was created with and what cloud pubsub documentation suggests.

Digging in code I discovered that Subscriber is created with maxAckExtensionPeriod defaulting to `com.google.cloud.pubsub.v1.Subscriber.Builder.DEFAULT_MAX_ACK_EXTENSION_PERIOD` which is 1 hour
I'd say this is undocumented but also undesirable default behaviour.

**Describe the solution you'd like**
I expect redelivery to happen with respect to `--ack-deadline` value and any acknowledgement extension to be performed only when explicitly configured when creating Subscription instance.

**Describe alternatives you've considered**
Set Duration.ZERO when creating Subscriber
`Subscriber.newBuilder(subscription, receiver).setMaxAckExtensionPeriod(Duration.ZERO).build`

**Additional context**
Additionally I've noticed that it is impossible to shut down Subscriber when maxAckExtensionPeriod is not zeroed and there is un-acked message 
By that I mean `subscriber.stopAsync.awaitTerminated()` blocks calling thread (for example shutdown hook thread) for as long as `maxAckExtensionPeriod` is, while Subscriber is still active and keeps receiving messages and calling MessageReceiver!

**Comment by hannahrogers-google** [comment]
Thanks for filing this bug @anthavio.  Please see our documentation for setting the maxAckExtensionPeriod: https://googleapis.dev/java/google-cloud-pubsub/latest/com/google/cloud/pubsub/v1/Subscriber.Builder.html#setMaxAckExtensionPeriod-org.threeten.bp.Duration-

We document here that the default maxAckExtensionPeriod is 1h. To disable auto deadline extensions, maxAckExtensionPeriod should be set to Duration.ZERO.
