### ISSUE TITLE
com.google.api.core.ApiFuture<String> should also return timestamp and not just message id

### ISSUE THREAD

**Issue by sumandatrika** [googleapis/java-pubsub#65]
I would like to know the timestamp of the message which was generated by the server when the message was published for one of my audit use cases as well as logging. Currently we only receive the message id, but would like to extend this to  object which can contain metadata of the message such as timestamp , message id (in future we can add any more information) rather than just returning string.

 public com.google.api.core.ApiFuture<String> publish(PubsubMessage message) should be 
 public com.google.api.core.ApiFuture<PubsubMessage> publish(PubsubMessage message) , whereas PubsubMessage should contain the server timestamp populated.

**Comment by hannahrogers-google** [comment]
Hi @sumandatrika, can you provide me with some more details about your particular use case (what exactly will the timestamps will be used for, do you need the exact time the server received the publish call or is an approximation OK, can you get the publish_timestamp from the PubsubMessage on the Subscribe side, etc.)

**Comment by sumandatrika** [comment]
I would like to know the exact timestamp when the message was published to the server from the producer perspective. This way i can have some audit metrics as to to how many messages were sent in a given Time-bucket Interval. I will also gauge the same metrics in the consumer for the same  time-bucket(Produced timestamp) to effectively calculate the message count between producer and consumer and it should be always the same.

**Comment by kamalaboulhosn** [comment]
Since this request is more of a service-wide request and not something limited to the Java client library, we will track it via the [issue tracker](https://issuetracker.google.com/issues/154851148).
