### ISSUE TITLE
GetSchema doesn't retrieve schema definition

### ISSUE THREAD

**Issue by pradn** [googleapis/java-pubsub#669]
The GetSchema call to the server can [set the SchemaView field](https://github.com/googleapis/java-pubsub/blob/134273dc751e3bfb23c77384c8173c7b693a9757/proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/GetSchemaRequest.java#L737). It defaults to BASIC, which doesn't return the schema definition. We should have set it to FULL, which retrieves the entire schema including the definition.

The test for Java GetSchema is [here](https://github.com/googleapis/java-pubsub/blob/134273dc751e3bfb23c77384c8173c7b693a9757/google-cloud-pubsub/src/test/java/com/google/cloud/pubsub/v1/SchemaServiceClientTest.java#L150). The test uses mocks, so it didn't catch the bug where we don't specify the SchemaView to be FULL.

We should set SchemaView to FULL [here](https://github.com/googleapis/java-pubsub/blob/134273dc751e3bfb23c77384c8173c7b693a9757/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/SchemaServiceClient.java#L332) and [here](https://github.com/googleapis/java-pubsub/blob/134273dc751e3bfb23c77384c8173c7b693a9757/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/SchemaServiceClient.java#L310).

**Comment by hannahrogers-google** [comment]
We are going to handle this change on the server side. Closing.
