### ISSUE TITLE
Samples does not have README.md

### ISSUE THREAD

**Issue by kamalaboulhosn** [googleapis/java-pubsub#744]
The main README.md file says "The samples' README.md has instructions for running the samples." But there is no such README.md file. We should make sure the instructions for running the samples are somewhere.

**Comment by hannahrogers-google** [comment]
@anguillanneuf, do we have instructions somewhere for running java pubsub samples, or do we need to create new instructions in a README?

**Comment by anguillanneuf** [comment]
Good catch! I will add.
