### ISSUE TITLE
Make google-cloud-pubsub's Subscriber more unit test-friendly

### ISSUE THREAD

**Issue by joaoandremartins** [googleapis/java-pubsub#8]
While building [unit tests](https://github.com/spring-cloud/spring-cloud-gcp/pull/61) for the Spring Integration Pub/Sub channel adapters, we needed to simulate the behaviour of a Subscriber receiving a message. The recommended way to do testing in google-cloud-pubsub seems to be to spin up a local emulator, according to [these instructions](https://github.com/GoogleCloudPlatform/google-cloud-java/blob/master/TESTING.md#testing-code-that-uses-pubsub), but the Cloud SDK is prohibitive to follow this approach.

I looked for a way to inject mocks into a Subscriber, but nothing seems to have the desired effect of triggering a received message.

**Comment by halilbilgin** [comment]
any update?

**Comment by hannahrogers-google** [comment]
This is part of a larger effort to make unit testing easier across all Pub/Sub client libraries.  Since this is a feature request that affects multiple libraries, we will track it via the [issue tracker](https://b.corp.google.com/issues/181876876).
