### ISSUE TITLE
Enable publish to multiple topics using one Publisher

### ISSUE THREAD

**Issue by chrisribble** [googleapis/java-pubsub#86]
**Is your feature request related to a problem? Please describe.**
We have to create a Publisher for each topic that we want to publish to. This is annoying because we create one topic per long-running operation that we are working on (to send reply messages for sub-tasks).

Over the course of a minute, each of our worker instances may need to publish to up to 600  different topics. This means that we have to maintain a cache of Publisher objects (one per topic) which we constantly thrash (since we don't want to have hundreds of these in memory). It also means that we have to jump through hoops to use the same ExecutorService so that we don't continuously create/destroy threads (and so that we don't have hundreds of threads running at a time just for publishing messages).

**Describe the solution you'd like**
The Publisher.Builder interface should allow creation of a Publisher without specifying the target topic and there should be a publish method which accepts a topic name. If the Publisher is created without a topic, then it would be reasonable for the publish method which does not accept a topic to throw an exception (since forcing someone to pass the topic would be an API break).

**Describe alternatives you've considered**
1. Use FixedExecutorProvider and a cache of Publisher instances (what we do now)
2. Abandon the java-pubsub client entirely and just use the REST API to publish
3. Re-architect our application to use fewer topics (it is not possible to entirely eliminate dynamic topics, but we could potentially reduce the worst case from hundreds to tens)

**Additional context**
This is especially irritating with the release of gax-1.53.1 (pulled in when I update to google-cloud-storage-1.103.1 or >=google-cloud-core-1.92.3) since alternative (1) above no longer works. See https://github.com/googleapis/gax-java/issues/870

**Comment by kamalaboulhosn** [comment]
Since this is a feature request that affects not only the Java client library, but other libraries as well, we will track it via the [issue tracker](https://issuetracker.google.com/issues/154851748).
