### ISSUE TITLE
PubSub FlowControlSettings MaxOutstandingElementCount default undesirable behaviour

### ISSUE THREAD

**Issue by NickGrantX** [googleapis/java-pubsub#869]
#### Environment details

API: PubSub
OS: OSX & Linux
Java: 11
Pubsub version(s): java-pubsub v1.113.9

(Note: we are calling via Spring Google Cloud Pub/Sub library, and we raised an issue there, but that team kindly directed us towards yourselves, as they use java-pubsub library). Original issue raised is here: https://github.com/GoogleCloudPlatform/spring-cloud-gcp/issues/641

#### Steps to reproduce

  1. Allow large amount of messages to build up on a subscription (e.g. 40,000)
  2. Start subscriber with default consumer config / default flow control settings
  3. Observe that number of messages processed is many times more than number of messages which were waiting to be processed (e.g. 46,124 vs 40,000 for our example)

#### Code example

```java
public class MaxOutstandingElementCountBugDemo {
  private static AtomicInteger messageProcessedCount = new AtomicInteger();

  public static void main(String... args) throws Exception {
    String projectId = "your-project-id";
    String subscriptionId = "your-subscription-id";

    subscribeAsyncExample(projectId, subscriptionId);
  }

  public static void subscribeAsyncExample(String projectId, String subscriptionId) {
    ProjectSubscriptionName subscriptionName =
        ProjectSubscriptionName.of(projectId, subscriptionId);

    MessageReceiver receiver =
        (PubsubMessage message, AckReplyConsumer consumer) -> {
          try {
            Thread.sleep(20); // Simulates a modest amount of processing
          } catch (Exception e) {
            // Ignored
          }

          int currentCounterValue = messageProcessedCount.incrementAndGet();
 
          // This allows us to see that far too many messages are being processed, when there is a big backlog
          System.out.println("Received message running total: " + currentCounterValue);

          consumer.ack();
        };

    Subscriber subscriber = null;
    try {
      subscriber = Subscriber.newBuilder(subscriptionName, receiver).build();
      subscriber.startAsync().awaitRunning();
      System.out.printf("Listening for messages on %s:\n", subscriptionName.toString());

      subscriber.awaitTerminated(300, TimeUnit.SECONDS);
    } catch (TimeoutException timeoutException) {
      subscriber.stopAsync();
    }
  }
}
```

#### Stack trace
```
N/A
```

#### Any additional information below
Here we start with 40,000 messages queued up...
<img width="662" alt="Screenshot 2021-10-05 at 12 25 07" src="https://user-images.githubusercontent.com/41681172/136013940-488ccd7b-a69f-4197-9a55-ba5078772ea8.png">

Then you can see we end up with 46,124 being processed (we see them now on another queue) because of undesirable behaviour...
<img width="660" alt="Screenshot 2021-10-05 at 12 24 31" src="https://user-images.githubusercontent.com/41681172/136013947-6b0137de-55ad-4c15-99d9-ec02519cbeea.png">

We can get it to 'behave' how we want by calling `FlowControlSettings.setMaxOutstandingElementCount` but it would seem counter-intuitive to us that we'd have to do that, in order that we shouldn't end up with messages processed more than once when our processing of an individual message is "quick".

We could also increase the acknowledgement deadline, but again that seems counter-intuitive, because each instance of a message we process is taking a lot less than the deadline.

**Comment by kamalaboulhosn** [comment]
Is this still an issue? If so, can you please explain the second graph that shows 46,124 messages? Is it for a different topic to which you published from the subscriber? It could be that the duplication didn't happen on the subscribe side; it happened on the publish side.

**Comment by maitrimangal** [comment]
Closing this issue. Please re-open if its still an issue.
