### ISSUE TITLE
Setting credentials on  Publisher results in com.google.api.gax.rpc.UnauthenticatedException

### ISSUE THREAD

**Issue by pax95** [googleapis/java-pubsub#930]
Publishing messages with ordered delivery and gcp regional endpoint results in UnauthenticatedException.

#### Environment details
java version 11
pubsub version 1.114.7

#### Code example

```j
public class Pubsubs {
    public static void main(String... args) throws Exception {
        // TODO(developer): Replace these variables before running the sample.
        String projectId = "some-project-id";
        // Choose an existing topic.
        String topicId = "demotopic";

        publishWithOrderingKeysExample(projectId, topicId);
    }

    public static void publishWithOrderingKeysExample(String projectId, String topicId)
        throws IOException, InterruptedException, ExecutionException {
        TopicName topicName = TopicName.of(projectId, topicId);
        // Create a publisher and set message ordering to true.
        File initialFile = new File("/demo/mykey.json");
        InputStream targetStream = new FileInputStream(initialFile);
        CredentialsProvider credentialsProvider = FixedCredentialsProvider.create(ServiceAccountCredentials.fromStream(targetStream));

        Publisher publisher =
            Publisher.newBuilder(topicName)
                // Sending messages to the same region ensures they are received in order
                // even when multiple publishers are used.
                .setEndpoint("us-east1-pubsub.googleapis.com:443")
                .setCredentialsProvider(credentialsProvider)
                .setEnableMessageOrdering(true)
                .build();

        try {
            Map<String, String> messages = new HashMap<String, String>();
            messages.put("message1", "key1");
            messages.put("message2", "key2");
            messages.put("message3", "key1");
            messages.put("message4", "key2");

            for (Map.Entry<String, String> entry : messages.entrySet()) {
                ByteString data = ByteString.copyFromUtf8(entry.getKey());
                PubsubMessage pubsubMessage =
                    PubsubMessage.newBuilder().setData(data).setOrderingKey(entry.getValue()).build();
                ApiFuture<String> future = publisher.publish(pubsubMessage);

                // Add an asynchronous callback to handle publish success / failure.
                addCallback(
                    future,
                    new ApiFutureCallback<String>() {

                        @Override
                        public void onFailure(Throwable throwable) {
                            if (throwable instanceof ApiException) {
                                ApiException apiException = ((ApiException)throwable);
                                // Details on the API exception.
                                System.out.println(apiException.getStatusCode().getCode());
                                System.out.println(apiException.isRetryable());
                                System.out.println(throwable);
                            }
                            System.out.println("Error publishing message : " + pubsubMessage.getData());
                        }

                        @Override
                        public void onSuccess(String messageId) {
                            // Once published, returns server-assigned message ids (unique within the topic).
                            System.out.println(pubsubMessage.getData() + " : " + messageId);
                        }
                    },
                    MoreExecutors.directExecutor());
            }
        } finally {
            // When finished with the publisher, shutdown to free up resources.
            publisher.shutdown();
            publisher.awaitTermination(1, TimeUnit.MINUTES);
        }
    }
}

```

#### Stack trace
```
com.google.api.gax.rpc.UnauthenticatedException: io.grpc.StatusRuntimeException: UNAUTHENTICATED: Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.
Error publishing message : <ByteString@1fd83bcb size=8 contents="message4">
Error publishing message : <ByteString@3ed2b13b size=8 contents="message3">
UNAUTHENTICATED
```

**Comment by meredithslota** [comment]
Thanks so much for your report! I'm not sure if this is an error in the code you shared or a bug in the library or something else but I've asked @anguillanneuf to take a look.

**Comment by pax95** [comment]
@meredithslota Thanks. 
The code I share is actually mostly taken from pubsub documentation here https://cloud.google.com/pubsub/docs/samples/pubsub-publish-with-ordering-keys only adding the credentialsProvider to the Publisher.

**Comment by anguillanneuf** [comment]
@pax95 It looks like you may not have set your credentials correctly for the client library to call the Pub/Sub service. Can you check the following?

1. `echo $GOOGLE_APPLICATION_CREDENTIALS`
2. `cat {your-key-file.json}`. Note which service account email in your `client_email`.
3. Check that your service account has the appropriate roles (that have appropriate permissions): 

```
export PROJECT=$(gcloud config get-value project)
export EMAIL= .. // your service account email

gcloud projects get-iam-policy $PROJECT \
  --format="table(bindings.members,bindings.role)" \
  --flatten="bindings[].members" \
  --filter="bindings.members=serviceAccount:$EMAIL"
```

**Comment by pax95** [comment]
@anguillanneuf I was trying to set the credentials using the FixedCredentialsProvider that loads the credentials file using a FileInputStream and creating a CredentialsProvider that can be set on the Publisher. See example above. This should be supported by the pubsub library, but seems not to work. 
This is to avoid to having to set the GOOGLE_APPLICATION_CREDENTIALS environment variable.

**Comment by anguillanneuf** [comment]
> At least it doesn't work if you use use a dedicated endpoint, (setting the pubsub endpoint to eg "us-east1-pubsub.googleapis.com:443") , but works when not setting it.

@pax95 I believe is WAI (working as intended). Not specifying a regional endpoint is equivalent to using `pubsub.googleapois.com:443`, which the credentials have scope for. 

If you can tell us more about your need, perhaps we can add this as a feature request for the service. Thanks for making us aware of this issue.

**Comment by pax95** [comment]
@anguillanneuf Actually I'm just following the pubsub documentation of how to publish messages with message ordering as described here https://cloud.google.com/pubsub/docs/samples/pubsub-publish-with-ordering-keys#pubsub_publish_with_ordering_keys-java 

where it states ->
           // Sending messages to the same region ensures they are received in order
            // even when multiple publishers are used. 

The same is described in the blog post https://medium.com/google-cloud/google-cloud-pub-sub-ordered-delivery-1e4181f60bc8
`It is important to remember that ordering guarantees are only for messages published in the same region. Therefore, it is highly recommended that all publishers use regional service endpoints to ensure they publish messages to the same region for the same ordering key.`

The example is only modified by setting the credentials provider on the Publisher. 

For me it seems that it is not WAI since I'm following the official documentation here.

**Comment by anguillanneuf** [comment]
@pax95 You're absolutely right about using regional endpoint to ensure ordered messages. I was hoping to understand why the need to avoid using an environment variable in your case. 

@hannahrogers-google Do we need to modify some of the defaults used in `Publisher`?

https://github.com/googleapis/java-pubsub/blob/04297f2318272b8a5dc981effce6077f6193130e/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/Publisher.java#L726-L727

**Comment by hannahrogers-google** [comment]
Hi @pax95, I believe you will need to add scopes to the Credentials. See the following changes:

```
ImmutableList<String> scopes = ImmutableList.<String>builder()
    .add("https://www.googleapis.com/auth/cloud-platform")
    .add("https://www.googleapis.com/auth/pubsub")
    .build();

File initialFile = new File("/demo/mykey.json");
InputStream targetStream = new FileInputStream(initialFile);
CredentialsProvider credentialsProvider =
    FixedCredentialsProvider.create(
        ServiceAccountCredentials.fromStream(targetStream).createScoped(scopes));

Publisher publisher =
    Publisher.newBuilder(topicName)
        // Sending messages to the same region ensures they are received in order
        // even when multiple publishers are used.
        .setEndpoint("us-east1-pubsub.googleapis.com:443")
        .setCredentialsProvider(credentialsProvider)
        .setEnableMessageOrdering(true)
        .build();
```

**Comment by anguillanneuf** [comment]
@pax95 I verified the code snippet @hannahrogers-google provided above. Thanks again for your question.

**Comment by nagarro-rishabh-rastogi** [comment]
Good question @pax95. I was facing the same issue until I found this thread. 

The sad part is that official documentation has not been updated to date. 

Relates to [GCP Pub/Sub | Publish Messages to a regional endpoint](https://stackoverflow.com/questions/76564006/gcp-pub-sub-publish-messages-to-a-regional-endpoint)

**Comment by rastogirishabh** [comment]
Good question @pax95. I was facing the same issue until I found this thread. 

The sad part is that official documentation has not been updated to date. 

Relates to [GCP Pub/Sub | Publish Messages to a regional endpoint](https://stackoverflow.com/questions/76564006/gcp-pub-sub-publish-messages-to-a-regional-endpoint)
