### ISSUE TITLE
PubSub - 1.115.0 crashes JVM on JDK/JRE 17 

### ISSUE THREAD

**Issue by busches** [googleapis/java-pubsub#947]
#### Environment details

2. OS type and version: Alpine 3.10-3.15
3. Java version:
-  JRE version: OpenJDK Runtime Environment (17.0.1+12) (build 17.0.1+12-alpine-r0)
-  Java VM: OpenJDK 64-Bit Server VM (17.0.1+12-alpine-r0, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
4. pubsub version(s): Starting with 1.115.0, 1.115.1, 1.115.2, 1.115.3, 1.115.4, 1.115.5

#### Steps to reproduce

  1. Upgrade from `com.google.cloud:google-cloud-pubsub:1.114.7` to `1.115.0`
  2. Try to use the library (or as seen here https://github.com/busches/gcp-pubsub-crash just start the app with it on the path)

#### Stack trace
```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x0000000000003efe, pid=11333, tid=11339
#
# JRE version: OpenJDK Runtime Environment (17.0.1+12) (build 17.0.1+12-alpine-r0)
# Java VM: OpenJDK 64-Bit Server VM (17.0.1+12-alpine-r0, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
# Problematic frame:
# C  0x0000000000003efe
#
```

```
/src # ldd /tmp/libio_grpc_netty_shaded_netty_transport_native_epoll_x86_6415072523310110693670.so
        /lib/ld-musl-x86_64.so.1 (0x7f5c0dd4f000)
        librt.so.1 => /lib/ld-musl-x86_64.so.1 (0x7f5c0dd4f000)
        libdl.so.2 => /lib/ld-musl-x86_64.so.1 (0x7f5c0dd4f000)
        libc.so.6 => /lib/ld-musl-x86_64.so.1 (0x7f5c0dd4f000)
Error relocating /tmp/libio_grpc_netty_shaded_netty_transport_native_epoll_x86_6415072523310110693670.so: __strdup: symbol not found
Error relocating /tmp/libio_grpc_netty_shaded_netty_transport_native_epoll_x86_6415072523310110693670.so: __strndup: symbol not found
```
```
/src # readelf -d /tmp/libio_grpc_netty_shaded_netty_transport_native_epoll_x86_6415072523310110693670.so

Dynamic section at offset 0xfd98 contains 23 entries:
  Tag        Type                         Name/Value
 0x0000000000000001 (NEEDED)             Shared library: [librt.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libdl.so.2]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
 0x000000000000000e (SONAME)             Library soname: [libnetty_transport_native_epoll_x86_64-4.1.63.Final.so]
 0x000000000000000c (INIT)               0x3b70
 0x000000000000000d (FINI)               0xb618
 0x000000006ffffef5 (GNU_HASH)           0x1b8
 0x0000000000000005 (STRTAB)             0x938
 0x0000000000000006 (SYMTAB)             0x200
 0x000000000000000a (STRSZ)              885 (bytes)
 0x000000000000000b (SYMENT)             24 (bytes)
 0x0000000000000003 (PLTGOT)             0x20ff88
 0x0000000000000002 (PLTRELSZ)           1488 (bytes)
 0x0000000000000014 (PLTREL)             RELA
 0x0000000000000017 (JMPREL)             0x35a0
 0x0000000000000007 (RELA)               0xdf8
 0x0000000000000008 (RELASZ)             10152 (bytes)
 0x0000000000000009 (RELAENT)            24 (bytes)
 0x000000006ffffffe (VERNEED)            0xd48
 0x000000006fffffff (VERNEEDNUM)         2
 0x000000006ffffff0 (VERSYM)             0xcae
 0x000000006ffffff9 (RELACOUNT)          415
 0x0000000000000000 (NULL)               0x0
```

**Comment by busches** [comment]
I was able to recreate this on 1.115.1 still. I was also able to recreate it on JDK 11.

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x0000000000003efe, pid=3563, tid=3568
#
# JRE version: OpenJDK Runtime Environment (11.0.4+4) (build 11.0.4+4-alpine-r1)
# Java VM: OpenJDK 64-Bit Server VM (11.0.4+4-alpine-r1, mixed mode, tiered, compressed oops, g1 gc, linux-amd64)
# Problematic frame:
# C  0x0000000000003efe
```

**Comment by busches** [comment]
To provide more detail, here's the code we're running:

```kotlin
    private var internalPublisher: Publisher?

    init {
        val channel = ManagedChannelBuilder.forTarget("localhost:7000").usePlaintext().build()
        val channelProvider = FixedTransportChannelProvider.create(GrpcTransportChannel.create(channel))
        val credentialsProvider = NoCredentialsProvider.create()

        val topicName = ProjectTopicName.of(project, topic)

        // GCP docs say to create this, but they don't use the variable for anything, having it changes nothing
        TopicAdminClient.create(
            TopicAdminSettings.newBuilder()
                .setTransportChannelProvider(channelProvider)
                .setCredentialsProvider(credentialsProvider)
                .build()
        )

        internalPublisher = Publisher.newBuilder(topicName)
            .setChannelProvider(channelProvider)
            .setCredentialsProvider(credentialsProvider)
            .build()
    }
```

Based off this example: https://cloud.google.com/pubsub/docs/emulator#accessing_environment_variables

And here's the coredump: [hs_err_pid329.log](https://github.com/googleapis/java-pubsub/files/7960339/hs_err_pid329.log)

Again this happens only with 1.115.0 (or higher), doesn't happen with 1.114.7.
Happens on JDK 11 or 17
Happens on Alpine 3.10 and 3.15 (latest).

If this is an Alpine issue, I can report it there, but since the change is in versions of the PubSub library, it seems related to this.

**Comment by busches** [comment]
Still broken with 1.115.3

**Comment by busches** [comment]
Still broken with 1.115.4

**Comment by busches** [comment]
Still broken with 1.115.5

**Comment by elefeint** [comment]
These issues may be related: netty/netty#11879, googleapis/java-secretmanager#692

@busches Do you happen to have a more detailed stack trace from the crash dump?

**Comment by busches** [comment]
@elefeint if this isn't what you're after, can you send an example? [hs_err_pid329.log](https://github.com/googleapis/java-pubsub/files/7960339/hs_err_pid329.log) There is no java stacktrace itself, just the JVM crash.

**Comment by elefeint** [comment]
Sorry, I missed the link when reading. This is it.
1) Are you using the [Libraries BOM](https://cloud.google.com/java/docs/bom) to manage versions Pub/Sub versions? That would be the first thing to try rather than hardcoding the specific client library version.

2) Your crash dump matches this issue exactly: netty/netty-tcnative#649. Switching to `alpine-slim` image resolved the issue for them.

**Comment by busches** [comment]
@elefeint We're using the Spring BOM
```
extra["springCloudGcpVersion"] = "3.1.0"
extra["springCloudVersion"] = "2021.0.0"

dependencyManagement {
  imports {
    mavenBom("com.google.cloud:spring-cloud-gcp-dependencies:${property("springCloudGcpVersion")}")
    mavenBom("org.springframework.cloud:spring-cloud-dependencies:${property("springCloudVersion")}")
  }
}
```

Which then brings in the BOM you linked: https://github.com/GoogleCloudPlatform/spring-cloud-gcp/blob/main/spring-cloud-gcp-dependencies/pom.xml

**Comment by busches** [comment]
Here is a simple reproduction: https://github.com/busches/gcp-pubsub-crash 
Run:
```
docker-compose up --build
```

And you will see it immediately crashes.

**Comment by busches** [comment]
I made my reproduction even easier, using Google's Bom: https://github.com/busches/gcp-pubsub-crash/blob/main/build.gradle.kts and then another using Spring Boot https://github.com/busches/gcp-pubsub-crash/blob/spring-boot-failure/build.gradle.kts

**Comment by busches** [comment]
Still present in 1.116.0

**Comment by KasperKiiskinen** [comment]
I think I'm running into same problem: https://github.com/adoptium/adoptium-support/issues/465
[error.txt](https://github.com/googleapis/java-pubsub/files/8261628/error.txt)

**Comment by elefeint** [comment]
grpc/grpc-java#8751 seems to be the same issue. Try the `LD_PRELOAD` workaround described [here](https://github.com/grpc/grpc-java/issues/8751#issuecomment-998199569).

**Comment by ncopa** [comment]
> 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]

The problem is that `/tmp/libio_grpc_netty_shaded_netty_transport_native_epoll_x86_6415072523310110693670.so` is linked to GNU libc (libc.so.6). It needs to be rebuidt with musl libc.

**Comment by ivangrujic09** [comment]
Still having issues on 1.120.0

**Comment by nis130** [comment]
Still facing the same issue, Any solid solution?

**Comment by kamalaboulhosn** [comment]
Based on https://github.com/grpc/grpc-java/issues/8751, it looks like the long-term workaround remains the use of `LD_PRELOAD`. For follow-up on the issue, please use the grpc repo ticket.

**Comment by kimnamcham** [comment]
still crash with docker image: eclipse-temurin:17-jre-alpine

with dependcy: 
    <dependency>
      <groupId>com.google.cloud</groupId>
      <artifactId>spring-cloud-gcp-pubsub</artifactId>
      <version>4.5.1</version>
      <scope>compile</scope>
    </dependency>
