### ISSUE TITLE
Running Sample code in Cloud Shell

### ISSUE THREAD

**Issue by satishrao84** [googleapis/java-pubsub#950]
I am brand new to GCP world. I am trying to run one of the pubsub examples (https://github.com/googleapis/java-pubsub/blob/HEAD/samples/snippets/src/main/java/pubsub/SubscribeWithAvroSchemaExample.java) in your Github repo on Cloud Shell.

I am able to build on the cloud shell by running `mvn clean install`. But when I run that Java class SubscribeWithAvroSchemaExample.java (after filling in the project id and subscrption id), I get the below error

> satish_anupindi84@cloudshell:~$ cd '/home/satish_anupindi84' && env
> '/usr/lib/jvm/java-11-openjdk-amd64/bin/java' '-Dfile.encoding=UTF-8'
> '-cp'
> '/home/satish_anupindi84/.theia/workspace-storage/e742f48ad7fde7236560e8cf9e48d278/redhat.java/jdt_ws/jdt.ls-java-project/bin'
> 'pubsub.SubscribeWithAvroSchemaExample' Exception in thread "main"
> java.lang.Error: Unresolved compilation problem:
> 
>     at pubsub.SubscribeWithAvroSchemaExample.main(SubscribeWithAvroSchemaExample.java:39)

Would someone try this out and let me know what they get? Any idea why I get this error?

**Comment by satishrao84** [comment]
Have attached a fil
<img width="1558" alt="Screen Shot 2021-12-16 at 12 19 56 PM" src="https://user-images.githubusercontent.com/20402373/146440633-1f68e4de-91f0-4017-8ccc-84ef6af0a7f4.png">
e

**Comment by satishrao84** [comment]
Someone please help! This is a pretty basic question... not sure if something in my project isn't set up correctly.

**Comment by meredithslota** [comment]
This sample is further described here: https://cloud.google.com/pubsub/docs/pull#java_5 Does your topic already have a schema configured? https://cloud.google.com/pubsub/docs/schemas We won't have visibility into your project settings — for project-specific debugging, please create an issue in the [support console](https://cloud.google.com/support/) instead.

**Comment by anguillanneuf** [comment]
@satishrao84 How are you running the sample? These steps worked for me just now:

1. Click the "OPEN IN GOOGLE CLOUD SHELL" button next to "Subscribe Async Example" in https://github.com/googleapis/java-pubsub#samples
2. Head over the Cloud Shell, navigate to `cloudshell_open/java-pubsub/samples/snippets/src/main/java/pubsub/SubscribeAsyncExample.java`, update the project and subscription ID in the Java script. 
3. In the Cloud Shell terminal, run `mvn compile exec:java -Dexec.mainClass=pubsub.SubscriberAsyncExample`.
