### ISSUE TITLE
Decouple Publisher Client and publishing Topic 

### ISSUE THREAD

**Issue by nitinchauhan178** [googleapis/java-pubsub#982]
**Is your feature request related to a problem? Please describe.**
Currently Publisher client is bind to a single topic. This require to create dedicated publisher clients for each topic we want to publish. We have use case where we need to publish to multiple topic (few hundreds) and for that we need to keep track of huge list of clients on VM memory.

**Describe the solution you'd like**
Decouple Publisher client with topic to publish. Topic information should be taken as arg to publish method as [TopicName](https://googleapis.dev/java/google-cloud-pubsub/latest/com/google/pubsub/v1/TopicName.html)

**Describe alternatives you've considered**
There is an alternative for it **TopicAdminClient.publish** which doesn't bind to a topic and a single client is able to publish to n number of topics. But this not recommended for high volume message publish and therefore not fulfilling our use case.

**Comment by maitrimangal** [comment]
We have moved this issue to our internal tracking system. However, the issue is considered low-priority at this time. If the issue is ultimately resolved, it will appear in the release notes for the client at that time. If this issue is of higher priority for you, please enter a support ticket for follow-up. Thanks

Internal Bug - b/278075996

**Comment by anthonyalayo** [comment]
@maitrimangal how does it look in terms of priority today? I am facing the same scenario and I agree with the issue.

I have a similar-ish discussion on the C++ side:
https://github.com/googleapis/google-cloud-cpp/issues/13707

**Comment by anthonyalayo** [comment]
@maitrimangal how do I file a support ticket for raising the priority?

**Comment by michaelpri10** [comment]
Hello @anthonyalayo, I support ticket can be filed in the [support console](https://cloud.google.com/support/). I will note that this feature request is still tracked on our [public issue tracker](https://b.corp.google.com/issues/154851748) as it would affect client libraries for other languages as well, and it has not currently been re-prioritized.
